### ISSUE TITLE
Error when executing jcli config

### ISSUE THREAD

**Issue by yJunS** [jenkins-zh/jenkins-cli#82]
This is my first time to execute this cmd. Error output is below:
```
2019/07/27 11:40:48 No config file found.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x13a1945]

goroutine 1 [running]:
github.com/linuxsuren/jenkins-cli/app/cmd.glob..func2(0x1805020, 0xc000091060, 0x1, 0x1)
	/Users/mac/go/src/github.com/linuxsuren/jenkins-cli/app/cmd/config.go:30 +0xd5
github.com/spf13/cobra.(*Command).execute(0x1805020, 0xc000091020, 0x1, 0x1, 0x1805020, 0xc000091020)
	/Users/mac/go/src/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0x1809760, 0x147de42, 0x1, 0x0)
	/Users/mac/go/src/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/mac/go/src/github.com/spf13/cobra/command.go:800
github.com/linuxsuren/jenkins-cli/app/cmd.Execute()
	/Users/mac/go/src/github.com/linuxsuren/jenkins-cli/app/cmd/root.go:40 +0x32
main.main()
	/Users/mac/go/src/github.com/linuxsuren/jenkins-cli/main.go:8 +0x20
```

**Comment by LinuxSuRen** [comment]
fixed at Version: v0.0.16
